# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_opinion'),
        ('main', '0004_userprofile'),
    ]

    operations = [
    ]
