# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models
import main.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20180321_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to='main.UserProfile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='main.UserProfile', verbose_name='نظرگیرنده'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='teller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, storage=main.storage.OverwriteStorage(), upload_to=main.models.image_path),
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='main.UserProfile'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter', to='main.UserProfile'),
        ),
    ]
