# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-06 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180331_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate2', to='main.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='TheMost2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Candidate')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter2', to='main.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='the_most',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TheMost2'),
        ),
        migrations.AlterUniqueTogether(
            name='vote2',
            unique_together=set([('voter', 'candidate')]),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together=set([('the_most', 'candidate')]),
        ),
    ]
