# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-06 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180406_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote2',
            name='the_most',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_most2', to='main.TheMost'),
        ),
        migrations.AlterField(
            model_name='vote2',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate3', to='main.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='vote2',
            unique_together=set([('voter', 'the_most')]),
        ),
    ]
