# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-01 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180406_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
